name: Actualizar Lista M3U

on:
  schedule:
    - cron: "0 */3 * * *" # Se ejecuta cada 3 horas
  workflow_dispatch: # Permite ejecutarlo manualmente cuando quieras

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Instalar librerías
        run: |
          pip install playwright
          playwright install chromium

      - name: Ejecutar script de extracción
        run: python extractor.py

      - name: Subir cambios
        run: |
          git config --local user.email "accion@github.com"
          git config --local user.name "GitHub Action"
          git add lista.m3u
          git diff --quiet && git diff --staged --quiet || git commit -m "Actualizacion automatica de lista M3U"
          git push
